language: node_js
sudo: required
node_js:
    - 'node'
    - 'lts/*'
    - '7.10'

os:
    - linux

cache:
    directories:
        - node_modules

addons:
    apt:
        packages:
            - xvfb
            - gnome-keyring
            - libsecret-1-dev
            - python-gnomekeyring

script:
    - npm test
