language: node_js
sudo: required
node_js:
    - 'node'
    - 'lts/*'
    - '7.10'

os:
    - linux
    - osx

cache:
    directories:
        - node_modules

script:
    - npm test

after_success:
    - du -sh dist
    - du -sh node_modules
