language: node_js
sudo: required
node_js:
    - 'node'
    - 'lts/*'
    - '7.10'

os:
    - linux

cache:
    directories:
        - node_modules

addons:
    apt:
        packages:
            - xvfb
            - gnome-keyring
            - libsecret-1-dev
            - python-gnomekeyring

before_script:
    - |
        if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
          dbus-launch /usr/bin/python -c "import gnomekeyring;gnomekeyring.create_sync('login', '');"
          eval $(echo -n "" | /usr/bin/gnome-keyring-daemon --login)
          eval $(/usr/bin/gnome-keyring-daemon --components=secrets --start)
          export GNOME_KEYRING_CONTROL GNOME_KEYRING_PID GPG_AGENT_INFO SSH_AUTH_SOCK
        fi

script:
    - npm test
