language: node_js
node_js:
  - '7.0'
  - 'node'

cache:
  directories:
    - node_modules

notifications:
  email: false
  slack:
    secure: "DFGhxNw5Ai4/P3Ur55RTgOIowejSzIbH9YFYatULUZfIRdXk8Zuo75n+xyysciqdGD4hV1jVZCecb37LRZtUiKPwsr7tRPsw5e7H7sb0M1FG1eVrupTZS+HwJ3/Dwg8B866JCGVOhniaaW4rDXLYn2n96H+2N60Su37VaYoHQPQfwSZuRp5QSRsHz6gAlIScYG4emOmREhmTw/x6K5GcT0k3Sv18uIWfrO9WTkCaUsVraT0f0LYkPGJNL91E8KYKrcX3/vGEFF8nL/JUyM3KexB/6OCG+0IxGcFlZ0FJAu2mTaEk6Y6S53u3NpoCjZTSPOA+ClHEfV52HrimpAsKBhY9VmuYkdlaJOLeRuxKvBma5VTOQf9zlWxcKeOf6ySWsxYfD8nFlwdIbcqOBTU4QeKQXUAOmmk8E/nbe+NBl02VI0A9n4P+QOMoedJjF9Ds+T98d4POAhzbvVH3igdB++w7/X/86JsJqVUnQXk7LE/qWiYDcPmIdFxKB4gUfQBS4e7KOqsCpN35b4Nrjex12Jk4sPYk9eQLBP1NxCn2A+y4Wm0WHN6MOoRrVC4CXHwz4r+hyVcGFthabG3uH+s7/EyG5nUESbaoYpwJ+5+yvYi/HyC7IcwPY6Cp2CnMfFMm3ROrrGw+MaVQxbkrpFen2UZe5wjkOJY2NmNTjaSQzvg="
    on_success: change
    on_failure: change

env:
  global:
    - DEPLOY_BRANCH='master'
    - DEPLOY_NODE_VERSION='node'
    - TEST_RUNNER=travis
