environment:
  matrix:
    - nodejs_version: "8.9.0"
    - nodejs_version: "10"

install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

# Don't actually build.
build: off
