CREATE TABLE `wp_users` (
    id INT(10) UNSIGNED NOT NULL AUTO_INCREMENTS,
    PRIMARY KEY(id);
) ENGINER=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `wp_users` (
    id INT(10) UNSIGNED NOT NULL AUTO_INCREMENTS,
    PRIMARY KEY(id);
) ENGINER=InnoDB DEFAULT CHARSET=utf8;
