//go:build parity

package parity

// Each case runs both real roots; expected writes are asserted independently.
var edgeWorkerScenarios = map[string]edgeWorkerCase{
	"edge-workers-init":                           {Fixture: "empty", State: "empty", WantPersistentOps: []string{}, WantExit: 0},
	"edge-workers-init-nonempty":                  {Fixture: "basic", State: "empty", WantPersistentOps: []string{}, WantExit: 1},
	"edge-workers-init-invalid-type":              {Fixture: "empty", State: "empty", WantPersistentOps: []string{}, WantExit: 1},
	"edge-workers-new":                            {Fixture: "basic", State: "empty", WantPersistentOps: []string{}, WantExit: 0},
	"edge-workers-new-location":                   {Fixture: "basic", State: "empty", WantPersistentOps: []string{}, WantExit: 0},
	"edge-workers-new-invalid-location":           {Fixture: "basic", State: "empty", WantPersistentOps: []string{}, WantExit: 1},
	"edge-workers-new-invalid-name":               {Fixture: "basic", State: "empty", WantPersistentOps: []string{}, WantExit: 1},
	"edge-workers-build-missing-compiler":         {Fixture: "basic", State: "empty", WantPersistentOps: []string{}, WantExit: 1},
	"edge-workers-build-empty":                    {Fixture: "no-workers", State: "empty", WantPersistentOps: []string{}, WantExit: 1},
	"edge-workers-build-name-all":                 {Fixture: "basic", State: "empty", WantPersistentOps: []string{}, WantExit: 1},
	"edge-workers-build-one":                      {Fixture: "compiler", State: "empty", WantPersistentOps: []string{}, WantExit: 0},
	"edge-workers-build-all":                      {Fixture: "two-compiler", State: "empty", WantPersistentOps: []string{}, WantExit: 0},
	"edge-workers-build-compiler-error":           {Fixture: "compiler-error", State: "empty", WantPersistentOps: []string{}, WantExit: 1},
	"edge-workers-list-table":                     {Fixture: "basic", State: "inactive", WantPersistentOps: []string{}, WantExit: 0},
	"edge-workers-list-csv":                       {Fixture: "basic", State: "inactive", WantPersistentOps: []string{}, WantExit: 0},
	"edge-workers-list-json":                      {Fixture: "basic", State: "inactive", WantPersistentOps: []string{}, WantExit: 0},
	"edge-workers-list-empty":                     {Fixture: "basic", State: "empty", WantPersistentOps: []string{}, WantExit: 0},
	"edge-workers-list-empty-json":                {Fixture: "basic", State: "empty", WantPersistentOps: []string{}, WantExit: 0},
	"edge-workers-get":                            {Fixture: "basic", State: "inactive", WantPersistentOps: []string{}, WantExit: 0},
	"edge-workers-get-source":                     {Fixture: "basic", State: "inactive", WantPersistentOps: []string{}, WantExit: 0},
	"edge-workers-get-empty-source":               {Fixture: "basic", State: "empty-source", WantPersistentOps: []string{}, WantExit: 0},
	"edge-workers-get-missing":                    {Fixture: "basic", State: "inactive", WantPersistentOps: []string{}, WantExit: 1},
	"edge-workers-read-null":                      {Fixture: "basic", State: "null-read", WantPersistentOps: []string{}, WantExit: 1},
	"edge-workers-validate":                       {Fixture: "basic", State: "empty", WantPersistentOps: []string{}, WantExit: 0},
	"edge-workers-validate-invalid":               {Fixture: "basic", State: "invalid-validation", WantPersistentOps: []string{}, WantExit: 1},
	"edge-workers-validate-all":                   {Fixture: "two-workers", State: "empty", WantPersistentOps: []string{}, WantExit: 0},
	"edge-workers-validate-name-all":              {Fixture: "basic", State: "empty", WantPersistentOps: []string{}, WantExit: 1},
	"edge-workers-validate-no-name":               {Fixture: "basic", State: "empty", WantPersistentOps: []string{}, WantExit: 1},
	"edge-workers-validate-no-artifact":           {Fixture: "no-artifact", State: "empty", WantPersistentOps: []string{}, WantExit: 1},
	"edge-workers-validate-null":                  {Fixture: "basic", State: "null-validation", WantPersistentOps: []string{}, WantExit: 1},
	"edge-workers-deploy-create":                  {Fixture: "basic", State: "empty", WantPersistentOps: []string{"create:headers"}, WantExit: 0},
	"edge-workers-deploy-create-enable":           {Fixture: "basic", State: "empty", WantPersistentOps: []string{"create:headers", "enable:headers"}, WantExit: 0},
	"edge-workers-deploy-inactive-update":         {Fixture: "basic", State: "inactive", WantPersistentOps: []string{"update:headers"}, WantExit: 0},
	"edge-workers-deploy-inactive-update-enable":  {Fixture: "basic", State: "inactive", WantPersistentOps: []string{"update:headers", "enable:headers"}, WantExit: 0},
	"edge-workers-deploy-active-update":           {Fixture: "basic", State: "active", WantPersistentOps: []string{"update:headers"}, WantExit: 0},
	"edge-workers-deploy-active-update-enable":    {Fixture: "basic", State: "active", WantPersistentOps: []string{"update:headers"}, WantExit: 0},
	"edge-workers-deploy-location-preserve":       {Fixture: "location-preserve", State: "inactive", WantPersistentOps: []string{"update:headers"}, WantExit: 0},
	"edge-workers-deploy-location-clear":          {Fixture: "location-clear", State: "inactive", WantPersistentOps: []string{"update:headers"}, WantExit: 0},
	"edge-workers-deploy-location-replace":        {Fixture: "location-replace", State: "inactive", WantPersistentOps: []string{"update:headers"}, WantExit: 0},
	"edge-workers-deploy-source-empty":            {Fixture: "source-empty", State: "empty", WantPersistentOps: []string{"create:headers"}, WantExit: 0},
	"edge-workers-deploy-skip-source":             {Fixture: "basic", State: "inactive", WantPersistentOps: []string{"update:headers"}, WantExit: 0},
	"edge-workers-deploy-all-preparation-failure": {Fixture: "two-workers", State: "invalid-second", WantPersistentOps: []string{}, WantExit: 1},
	"edge-workers-deploy-upload-failure":          {Fixture: "two-workers", State: "upload-second-fails", WantPersistentOps: []string{"create:a", "create:b"}, WantExit: 1},
	"edge-workers-deploy-enable-failure":          {Fixture: "two-workers", State: "enable-fails", WantPersistentOps: []string{"create:a", "enable:a"}, WantExit: 1},
	"edge-workers-deploy-production-refused":      {Fixture: "basic", State: "empty", WantPersistentOps: []string{}, WantExit: 1},
	"edge-workers-deploy-name-all":                {Fixture: "basic", State: "empty", WantPersistentOps: []string{}, WantExit: 1},
	"edge-workers-enable":                         {Fixture: "basic", State: "inactive", WantPersistentOps: []string{"enable:headers"}, WantExit: 0},
	"edge-workers-enable-production-refused":      {Fixture: "basic", State: "inactive", WantPersistentOps: []string{}, WantExit: 1},
	"edge-workers-disable":                        {Fixture: "basic", State: "active", WantPersistentOps: []string{"disable:headers"}, WantExit: 0},
	"edge-workers-delete-force":                   {Fixture: "basic", State: "inactive", WantPersistentOps: []string{"delete:headers"}, WantExit: 0},
	"edge-workers-delete-rejected":                {Fixture: "basic", State: "false-delete", WantPersistentOps: []string{"delete:headers"}, WantExit: 1},
	"edge-workers-mutation-null":                  {Fixture: "basic", State: "null-mutation", WantPersistentOps: []string{"enable:headers"}, WantExit: 1},
	"edge-workers-mutation-graphql-error":         {Fixture: "basic", State: "graphql-error", WantPersistentOps: []string{"enable:headers"}, WantExit: 1},
	"edge-workers-bare-path":                      {Fixture: "basic", State: "empty", WantPersistentOps: []string{}, WantExit: 1},
	"edge-workers-bare-location":                  {Fixture: "basic", State: "empty", WantPersistentOps: []string{}, WantExit: 1},
	"edge-workers-short-equals":                   {Fixture: "basic", State: "empty", WantPersistentOps: []string{}, WantExit: 0},
	"edge-workers-double-dash":                    {Fixture: "basic", State: "empty", WantPersistentOps: []string{}, WantExit: 0},
	"edge-workers-duplicate-names":                {Fixture: "duplicates", State: "empty", WantPersistentOps: []string{}, WantExit: 1},
	"edge-workers-entry-escape":                   {Fixture: "entry-escape", State: "empty", WantPersistentOps: []string{}, WantExit: 1},
	"edge-workers-artifact-symlink":               {Fixture: "artifact-symlink", State: "empty", WantPersistentOps: []string{}, WantExit: 1},
	"edge-workers-repeated-path":                  {Fixture: "basic", State: "empty", WantPersistentOps: []string{}, WantExit: 1},
	"edge-workers-repeated-type":                  {Fixture: "basic", State: "empty", WantPersistentOps: []string{}, WantExit: 1},
	"edge-workers-bare-type":                      {Fixture: "basic", State: "empty", WantPersistentOps: []string{}, WantExit: 1},
	"edge-workers-unicode-order":                  {Fixture: "unicode-compiler", State: "empty", WantPersistentOps: []string{}, WantExit: 0},
	"edge-workers-json-control-name":              {Fixture: "basic", State: "control-name", WantPersistentOps: []string{}, WantExit: 0},
	"edge-workers-table-control-name":             {Fixture: "basic", State: "control-name", WantPersistentOps: []string{}, WantExit: 0},
	"edge-workers-get-no-source":                  {Fixture: "basic", State: "no-source", WantPersistentOps: []string{}, WantExit: 0},
	"edge-workers-deploy-production-skip":         {Fixture: "basic", State: "empty", WantPersistentOps: []string{"create:headers"}, WantExit: 0},
	"edge-workers-deploy-skip-validate":           {Fixture: "basic", State: "empty", WantPersistentOps: []string{"create:headers"}, WantExit: 0},
	"edge-workers-deploy-skip-source-create":      {Fixture: "basic", State: "empty", WantPersistentOps: []string{"create:headers"}, WantExit: 0},
}
