name: Publish changelog
on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  publish-changelog:
    name: Publish changelog
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v5
      - uses: Automattic/vip-actions/changelog@64cb27606455c925183e07065f050846d69b2120
        with:
          endpoint: 'https://docs.wpvip.com/wp-json/wp/v2/changelogs'
          endpoint-token: ${{ secrets.CHANGELOG_DOCS_POST_TOKEN }}
          endpoint-auth-type: 'basic'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          status: 'publish'
          terms: changelog_category:110
          tag-id: '115'
          link-to-pr: false
          source: 'last-release'
