name: Public Changelog
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  changelog:
    name: Public Changelog
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - uses: Automattic/vip-actions/changelog@f083b1e1e0cd092ee5cafa6621d32a28c68bf7ee # trunk
        with:
          endpoint: ${{ env.CHANGELOG_POST_ENDPOINT }}
          endpoint-token: ${{ secrets.CHANGELOG_POST_TOKEN }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          status: 'draft'
          category-id: '26'
          link-to-pr: true
          source: 'last-release'
