name: Git Hash Security Check

on:
  pull_request:
  push:
    branches:
      - develop
      - trunk
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-git-hash-security:
    name: Verify Full Git Commit Hashes
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source code
        uses: actions/checkout@v7

      - name: Check for short git hashes in package.json
        uses: Automattic/vip-actions/git-hash-security-check@438cd00aac2463a2dbfb4a747ad7b1ac67a2575a # trunk
