name: Git Hash Security Check

on:
  pull_request:
  push:
    branches:
      - develop
      - trunk
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-git-hash-security:
    name: Verify Full Git Commit Hashes
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source code
        uses: actions/checkout@v6

      - name: Check for short git hashes in package.json
        uses: Automattic/vip-actions/git-hash-security-check@517cd5a53681c02f1eb4c490f1c2e095362de10f # trunk
