name: Publish prerelease to npm

on:
  workflow_dispatch:
    inputs:
      npm_tag:
        description: 'NPM tag for prerelease'
        default: 'next'

jobs:
  publish:
    name: Publish prerelease
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    steps:
      - uses: Automattic/vip-actions/npm-publish-prerelease@v0.6.0
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          PROVENANCE: 'true'
          NPM_TAG: ${{ inputs.npm_tag }}
        env:
          npm_config_tag: ${{ inputs.npm_tag }}
