name: Stale monitor

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    name: Stale
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: Automattic/vip-actions/stale@517cd5a53681c02f1eb4c490f1c2e095362de10f # trunk
