name: Stale monitor

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    name: Stale
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: Automattic/vip-actions/stale@63b6eb29cdcf8f55d7f0910c82356f34f8f997c4 # trunk
